### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ray10k** [hakuch/Nebula#8] opened 2015-10-04 13:09 UTC
I tried to install Nebula via opam, but the build process failed with the following error:

    # File "src/devices/monitor.ml", line 218, characters 2-12:
    # Error: Integer literal exceeds the range of representable integers of type int
    # Command exited with code 2.
    # Makefile:14: recipe for target 'nebula' failed

Looking into the source code, the referenced value is apparently the number of microseconds during which the startup screen is shown.
Strangely enough, the blink period right above it (1,000,000,000) did not raise this error, and the current value of the startup duration (1,300,000,000) should be representable with 31 bits.

**Comment by hakuch** [comment] 2015-10-04 16:13
Hi @ray10k .

Thanks for opening an issue!

could you please let me know your exact installed OCaml version and the platform that you're running on?

That will help me to reproduce the issue.

**Comment by hakuch** [comment] 2015-10-04 16:28
A minor correction: this is the number of _nanoseconds_ (1x10^-9) that the simulated monitor shows the start-up screen. It's not clear why the compiler is complaining, because as you pointed out, these literals are less than 2^31.

Once I have more information I might be able to learn more.

**Comment by ray10k** [comment] 2015-10-05 08:23
I'm running lubuntu as my operating system, a lightweight version of ubuntu 15.04.
OCaml 4.02.3

Side note, I had to semi-manually install opam due to some issue with the default version provided, in accordance with https://opam.ocaml.org/doc/Install.html under the heading Ubuntu.

**Comment by hakuch** [comment] 2015-10-05 13:18
Woops. OCaml uses a tagged pointer representation in its run-time which means that only 31 bits are available for signed integers.

That means that the range of allowable values is -2^30 to 2^30 - 1 on 32 bit systems. That upper bound is 1 073 741 823.

I'll try to fix this today.

**Comment by ray10k** [comment] 2015-10-05 13:22
OK. Also, just in case it could be an issue further down the line, I'll look into upgrading to a 64-bit version. Think the processor can handle it, anyway.

**Comment by hakuch** [comment] 2015-10-05 13:28
I'm going to close this ticket and track progress in #9. Feel free to continue the discussion there.

**Closed by hakuch** 2015-10-05 13:28 UTC
Labels: bug

**Comment by hakuch** [comment] 2015-10-06 00:49
@ray10k I think this has been fixed in `master`.  Please follow the instructions for [Installing from source](https://github.com/hakuch/Nebula#installing-from-source) and let me know if it's still failing to build.
